switched to `apex-enterprise-patterns/setup-sfdx@v2`
apex-enterprise-patterns/force-di pull request #95
Opened 2023-12-19 04:29 UTC by ImJohnMDaniel

2023-12-19 11:34 UTC, daveespo requested changes
> *[Reviewable](https://reviewable.io/reviews/apex-enterprise-patterns/force-di/95)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ImJohnMDaniel and @stohn777)

___
*[`.github/workflows/deploy.and.test.yml` line 26 at r1](https://reviewable.io/reviews/apex-enterprise-patterns/force-di/95#-Nm0qIaq7NakAQYDAgA-:-Nm0qIaq7NakAQYDAgA0:b-pbukp6) ([raw file](https://github.com/apex-enterprise-patterns/force-di/blob/5a8e0943dc91fa1f283be4e225b9e30f5e161e15/.github/workflows/deploy.and.test.yml#L26)):*
> ```YAML
>       # Setup the config parameters needed
>       - run: sf config set target-dev-hub SFDX-ENV --global #Even though the setup-sfdx action uses --setdefaultdevhubusername, it doesn't seem to stick since it uses --setdefaultusername so we brute force it here
>       # Create the scratch org
> ```

What's the reasoning with these rather uninformative comments in the YAML? Comments should only be used for unidiomatic code .. there's no mystery here as to what's going on

If you want to add the `name` property so that the log output in the GH UI is more palatable, that makes more sense .. 


<!-- Sent from Reviewable.io -->

2023-12-19 15:56 UTC, ImJohnMDaniel commented
> > _[Reviewable](https://reviewable.io/reviews/apex-enterprise-patterns/force-di/95)_ status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ImJohnMDaniel and @stohn777)
> 
> _[`.github/workflows/deploy.and.test.yml` line 26 at r1](https://reviewable.io/reviews/apex-enterprise-patterns/force-di/95#-Nm0qIaq7NakAQYDAgA-:-Nm0qIaq7NakAQYDAgA0:b-pbukp6) ([raw file](https://github.com/apex-enterprise-patterns/force-di/blob/5a8e0943dc91fa1f283be4e225b9e30f5e161e15/.github/workflows/deploy.and.test.yml#L26)):_
> 
> > ```yaml
> >       # Setup the config parameters needed
> >       - run: sf config set target-dev-hub SFDX-ENV --global #Even though the setup-sfdx action uses --setdefaultdevhubusername, it doesn't seem to stick since it uses --setdefaultusername so we brute force it here
> >       # Create the scratch org
> > ```
> 
> What's the reasoning with these rather uninformative comments in the YAML? Comments should only be used for unidiomatic code .. there's no mystery here as to what's going on
> 
> If you want to add the `name` property so that the log output in the GH UI is more palatable, that makes more sense ..

@daveespo, in my opinion, the comments help with the readability; nothing more.

2023-12-19 22:38 UTC, stohn777 commented on .github/workflows/deploy.and.test.yml
> +      - run: sf shane github src install --convert --githubuser apex-enterprise-patterns --repo force-di-samples --path force-app-1
Why are you installing each directory separately? Why not one instance of ...
`sf shane github src install --convert --githubuser apex-enterprise-patterns --repo force-di-samples --path sfdx-source`
Does Shane's plugin not work that way? `sf project deploy start -d sfdx-source/` would do so.

2023-12-19 22:43 UTC, stohn777 submitted a review, later dismissed

2023-12-20 03:33 UTC, daveespo approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/apex-enterprise-patterns/force-di/95)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ImJohnMDaniel)



<!-- Sent from Reviewable.io -->

2023-12-20 14:11 UTC, merged